### ISSUE TITLE
Vapor compression distillation

### ISSUE THREAD

**Issue by ottiker** [planetarytechnology/power-PV#3]
Basic steps, to purify water:
1. Heat water to 100°
2. Water flows to a Evaporator and is heated to a *little* more than 100° ([Evaporator](https://en.wikipedia.org/wiki/Evaporator))
3. Compress steam, raises temperature to a *little* more than 100° ([Steam ejector](https://en.wikipedia.org/wiki/Injector#Vacuum_ejectors))
4. Stream flows to a chamber, which walls have a temperature of 100° (Gas are vented out)
5. The Clean hot water gets cooled, by heating the incoming cold water ([Counter flow heat exchanger](https://en.wikipedia.org/wiki/Countercurrent_exchange))

[General description of the process](https://en.wikipedia.org/wiki/Vapor-compression_evaporation).

**Comment by ottiker** [comment]
Contact for DEKA Slingshot: https://www.betterworldsolutions.eu/portfolio/slingshot-the-ultimate-seawater-purifier/
This would be the ultimate solution!

**Comment by mauricebasement** [comment]
http://www.dekaresearch.com/innovations/ does mention the development of a Striling Engine at Deka Reasearch! We have to get in touch with them.

**Comment by mauricebasement** [comment]
wrong repo, please close
